name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - released

jobs:
  docker:
    name: Docker Images
    runs-on: ubuntu-22.04
    environment: build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Tag and push
        run: |
          set -ex

          echo prerelease
          echo ${{ github.event.release.prerelease}}
