name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - created
      - edited
      - published
      - prereleased
      - released

jobs:
  docker:
    name: Docker Images
    runs-on: ubuntu-22.04
    environment: build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Tag and push
        # For releases, we specifically do _not_ want to rebuild, just tag the
        # existing image and push. There's no officially maintained action for
        # this use case, but it's trivial enough to do ourselves.
        if: ${{ github.event_name == 'release' }}
        run: |
          echo $ {{ github }}
